[build-system]
requires = [
  "setuptools>=42.0.0",
  "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "lego-classifier"
version = "1.0.0"

[project.scripts]
lego = "lego_classifier.cli:app"

[tool.setuptools.packages.find]
where = ["."]